### ISSUE TITLE
LINUX / System Roles: Suggestion of less invasive system role

### ISSUE THREAD

**Issue by benblasco** [RedHatGov/product-demos#37]
The timesync system role would be a good example to demonstrate, with suggested vars to enter into the template:

```
system_roles:
  - timesync

timesync_ntp_servers:
  - hostname: au.pool.ntp.org
    pool: yes
    iburst: yes

```

This could be added as a second example in the suggested usage at: https://github.com/RedHatGov/product-demos/blob/main/linux/README.md
